output_template=/home/benjamin/Pictures/Screenshots/Screenshot From ${&-:%Y-%m-%d} ${&-:%H-%M-%S}.jpg
warn_about_template=no
output_format=mjpeg
create_directories=no
keep_original=no
disable_keybind=yes
