# Prefix
unbind C-b
set-option -g prefix C-v
bind-key C-v send-prefix
set -g mode-keys emacs
set -g status-keys emacs
set -s escape-time 0

# Split
bind 3 split-window -h
bind 2 split-window -v
bind k killp
unbind '"'
unbind %

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on
bind -T copy-mode MouseDragEnd1Pane send-keys -X copy-selection-no-clear

# Start at one
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

#prefix highlight
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'

set -g @prefix_highlight_fg 'black'
set -g @prefix_highlight_bg 'white'

# battery
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @batt_icon_charge_tier8 'Bat'
set -g @batt_icon_charge_tier7 'Bat'
set -g @batt_icon_charge_tier6 'Bat'
set -g @batt_icon_charge_tier5 'Bat'
set -g @batt_icon_charge_tier4 'Bat'
set -g @batt_icon_charge_tier3 'Bat'
set -g @batt_icon_charge_tier2 'LOW'
set -g @batt_icon_charge_tier1 'LOW'
set -g @batt_icon_status_charged 'Chr'
set -g @batt_icon_status_charging 'Chr'
set -g @batt_icon_status_discharging 'Dis'

# DESIGN TWEAKS

# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# -- Status Bar ---------------------------------------------

set -g status-position bottom
set -g status-interval 1

set -g status-left " #{session_name} - "
set -g status-left-length 50

if-shell '[ -z "$(acpi 2>/dev/null)" ]' {
    set -g status-right "#{prefix_highlight} %H:%M "
} {
    set -g status-right "#{prefix_highlight} #{battery_icon}: #{battery_percentage} - %H:%M "
}
set -g status-right-length 50

set-option -g status-justify left
set-option -g status-style "fg=white"
setw -g window-status-current-style 'fg=black bg=white'
setw -g window-status-current-format '#[bg=white] #I #[bg=black,fg=white,bold] #W '
setw -g window-status-style 'fg=white bg=black'
setw -g window-status-format '#[bg=color236] #I #[bg=black,fg=white] #W '

set -g set-titles off

set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[ q'

set -g message-style 'fg=white bg=red bold'

##
run '~/.tmux/plugins/tpm/tpm'
