Ctrl+r script-binding quality_menu/reload
F      script-binding quality_menu/video_formats_toggle
Alt+f  script-binding quality_menu/audio_formats_toggle

RIGHT seek 5 exact
LEFT seek -5 exact
UP seek 5 keyframes
DOWN seek -5 keyframes

] add speed 0.25
[ add speed -0.25
\ set speed 1

Shift+Alt+s script-binding crop-screenshot
