demuxer-max-bytes=1000000KiB

save-position-on-quit=no

input-ipc-server=/tmp/mpvsocket

screenshot-sw=no
screenshot-format=jpeg
screenshot-dir="~/Pictures/Screenshots/"
screenshot-template="Screenshot From %tY-%tm-%td %tH-%tM-%tS - MPV %wH.%wM.%wS.%wT (%f)"

alang=ja,jp,jpn,en,eng
slang=en,eng

vo=gpu-next
gpu-api=vulkan
hwdec=yes
osc=no
cursor-autohide=800

volume=100
volume-max=200

demuxer-mkv-subtitle-preroll=yes
sub-auto=fuzzy
