{
    "Fonts": [
        {
            "FontName": ".local/share/fonts/iosevka-comfy-normalregularupright.ttf",
            "FontSize": 18
        },
        {
            "FontName": "defaultMonoFont",
            "FontSize": 14
        }
    ],
    "TagFgColor": "#f6f3e8",
    "TagBgColor": "#2d2d2d",
    "TagPathBasenameColor": "#8fbfdc",
    "BodyFgColor": "#f6f3e8",
    "BodyBgColor": "#242424",
    "LayoutBoxFgColor": "#ff6f6f",
    "LayoutBoxUnsavedBgColor": "#ff6f6f",
    "LayoutBoxBgColor": "#444444",
    "ScrollFgColor": "#303030",
    "ScrollBgColor": "#444444",
    "ScrollBorderColor": "#444444",
    "GutterWidth": 14,
    "WinBorderColor": "#000000",
    "WinBorderWidth": 2,
    "PrimarySelectionFgColor": "#242424",
    "PrimarySelectionBgColor": "#8ac6f2",
    "ExecutionSelectionFgColor": "#242424",
    "ExecutionSelectionBgColor": "#e5786d",
    "SecondarySelectionFgColor": "#242424",
    "SecondarySelectionBgColor": "#f0e68c",
    "ErrorsTagFgColor": "#f6f3e8",
    "ErrorsTagBgColor": "#514444",
    "ErrorsTagPathBasenameColor": "#8fbfdc",
    "ErrorsTagFlashFgColor": "#f6f3e8",
    "ErrorsTagFlashBgColor": "#ff6f6f",
    "ErrorsTagFlashPathBasenameColor": "#8fbfdc",
    "TabStopInterval": 30,
    "TabStopPadding": 10,
    "Syntax": {
        "KeywordColor": "#8fbfdc",
        "NameColor": "#f6f3e8",
        "StringColor": "#99ad6a",
        "NumberColor": "#e5786d",
        "OperatorColor": "#f6f3e8",
        "CommentColor": "#888888",
        "PreprocessorColor": "#ac7ea8",
        "HeadingColor": "#99ad6a",
        "SubheadingColor": "#ac7ea8",
        "InsertedColor": "#99ad6a",
        "DeletedColor": "#e5786d"
    },
    "Ansi": {
        "Colors": [
            "#242424",
            "#e5786d",
            "#99ad6a",
            "#ffe377",
            "#8fbfdc",
            "#ac7ea8",
            "#8af6c7",
            "#f6f3e8",
            "#888888",
            "#e5786d",
            "#99ad6a",
            "#ffe377",
            "#8fbfdc",
            "#ac7ea8",
            "#8af6c7",
            "#ffffff"
        ]
    },
    "LineSpacing": 0,
    "TextLeftPadding": 3,
    "TextRightPadding": 3,
    "TextBottomPadding": 0,
    "TrayFgColor": "#f6f3e8",
    "TrayBgColor": "#2d2d2d",
    "TrayInnerBorderColor": "#000000",
    "TrayInnerBorderWidth": 2,
    "TrayOuterBorderColor": "#444444",
    "TrayOuterBorderWidth": 2,
    "CursorProg": "\ncolor(0,0,0,255);\nbegin;\nmove(-3,0);\nline(7,0);\nline(0,3);\nline(-2,0);\nline(0,lh);\nline(0,-6);\nline(2, 0);\nline(0, 3);\nline(-7, 0);\nline(0, -3);\nline(2, 0);\nline(0, -lh);\nline(0, 6);\nline(-2, 0);\nline(0, -3);\nclose;\ncolor(246,243,232,255);\nbegin;\nmove(-2, 1);\nline(5, 0);\nline(0, 1);\nline(-2, 0);\nline(0, lh);\nline(0, -4);\nline(2, 0);\nline(0, 1);\nline(-5, 0);\nline(0, -1);\nline(2, 0);\nline(0, -lh);\nline(0, 4);\nline(-2, 0);\nline(0, 1);\nclose;\n"
}
